# Generated by Django 4.1.2 on 2023-04-30 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalidadVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_calidad', models.CharField(max_length=255)),
                ('formato_estandarizado', models.CharField(max_length=255)),
                ('dimensiones', models.CharField(max_length=255)),
                ('resolucion', models.CharField(max_length=255)),
                ('codec_video', models.CharField(max_length=255, null=True)),
                ('codec_audio', models.CharField(max_length=255, null=True)),
                ('resolucion_max', models.CharField(max_length=255, null=True)),
                ('calidad_constante', models.PositiveSmallIntegerField(null=True)),
                ('fps', models.PositiveSmallIntegerField(null=True)),
                ('bit_rate_audio', models.PositiveIntegerField(null=True)),
                ('mix_audio', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CalificacionVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('descripcion', models.TextField()),
                ('contenedor_img', models.CharField(blank=True, max_length=2500, null=True)),
                ('no_videos', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ColeccionesVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coleccion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='EnlaceExternoVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enlace', models.TextField(max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='EstadosRepublica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EventoAcervo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=4000)),
                ('titulo', models.CharField(max_length=500)),
                ('duracion', models.PositiveIntegerField(default=0)),
                ('fechainicio', models.DateTimeField()),
                ('fechafin', models.DateTimeField()),
                ('contenedor_img', models.CharField(blank=True, max_length=2500, null=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_evento', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GenerosVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ListaReproduccionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('no_videos', models.PositiveIntegerField(default=0)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500, unique=True)),
                ('contenedor_aws', models.CharField(blank=True, max_length=4000, null=True)),
                ('contenedor_img', models.CharField(blank=True, max_length=2500, null=True)),
                ('visitas', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos_por_categoria', to='administracion.categorias')),
            ],
        ),
        migrations.CreateModel(
            name='VisitasVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitas', models.PositiveIntegerField(default=0)),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_por_visita', to=settings.AUTH_USER_MODEL)),
                ('id_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas_por_video', to='administracion.video')),
            ],
        ),
        migrations.CreateModel(
            name='VisitasEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitas', models.PositiveIntegerField(default=0)),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas_por_evento', to='administracion.eventoacervo')),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_por_visitas_evento', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerificacionRegistroUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=32, unique=True)),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
                ('vigencia_time', models.DateTimeField(blank=True, null=True)),
                ('utilizado', models.BooleanField(default=False)),
                ('is_reset', models.BooleanField(default=False)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListaReproduccionUsuarioVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_lista_reprod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.listareproduccionusuario')),
                ('id_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.video')),
            ],
        ),
        migrations.CreateModel(
            name='FavoritosUsuarioVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos_por_video', to='administracion.video')),
            ],
        ),
        migrations.CreateModel(
            name='CreditosVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_identificacion', models.CharField(max_length=255)),
                ('anio_produccion', models.PositiveSmallIntegerField(null=True)),
                ('contenedor_fotograma_aws', models.CharField(max_length=255, null=True)),
                ('sinopsis', models.CharField(max_length=4000)),
                ('direccion_realizacion', models.CharField(max_length=255)),
                ('asistentes_realizacion', models.CharField(max_length=500, null=True)),
                ('guion', models.CharField(max_length=500)),
                ('camara', models.CharField(max_length=500, null=True)),
                ('foto_fija', models.CharField(max_length=500, null=True)),
                ('color', models.BooleanField()),
                ('duracion_mins', models.PositiveSmallIntegerField()),
                ('reparto', models.CharField(max_length=1000, null=True)),
                ('testimonios', models.CharField(max_length=4000, null=True)),
                ('idioma', models.CharField(max_length=255, null=True)),
                ('musica', models.CharField(max_length=500, null=True)),
                ('performance', models.CharField(max_length=500, null=True)),
                ('edicion', models.CharField(max_length=500)),
                ('produccion_ejecutiva', models.CharField(max_length=500)),
                ('produccion', models.CharField(max_length=500, null=True)),
                ('pais', models.CharField(max_length=100, null=True)),
                ('id_video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creditos_por_video', to='administracion.video')),
            ],
        ),
        migrations.CreateModel(
            name='CreditosAdicionalesVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribuidor', models.CharField(max_length=500, null=True)),
                ('locaciones', models.CharField(max_length=4000, null=True)),
                ('coproduccion', models.CharField(max_length=500, null=True)),
                ('formato_master', models.CharField(max_length=500, null=True)),
                ('formato_videograbacion', models.CharField(max_length=255, null=True)),
                ('formatos_disponibles', models.CharField(max_length=255, null=True)),
                ('estado_conservacion', models.CharField(max_length=255, null=True)),
                ('tema', models.CharField(max_length=4000, null=True)),
                ('areas_contexto', models.CharField(max_length=4000, null=True)),
                ('idVideo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.video')),
                ('id_coleccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.coleccionesvideos')),
                ('id_enlace_externo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.enlaceexternovideo')),
                ('id_estado_republica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.estadosrepublica')),
                ('id_genero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.generosvideos')),
            ],
        ),
        migrations.CreateModel(
            name='ComentariosVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(null=True)),
                ('document_id', models.CharField(max_length=128)),
                ('parent_document_id', models.CharField(blank=True, max_length=128, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('id_autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_por_video', to='administracion.video')),
            ],
        ),
        migrations.AddIndex(
            model_name='categorias',
            index=models.Index(fields=['titulo'], name='idx_categoria_titulo'),
        ),
        migrations.AddField(
            model_name='calificacionvideo',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_calificacion_video', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calificacionvideo',
            name='id_video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_calificacion', to='administracion.video'),
        ),
        migrations.AddField(
            model_name='calidadvideo',
            name='id_video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.video'),
        ),
        migrations.AddIndex(
            model_name='visitasvideo',
            index=models.Index(fields=['id_usuario', 'id_video'], name='idx_visitas_usuario_video'),
        ),
        migrations.AddIndex(
            model_name='visitasevento',
            index=models.Index(fields=['id_usuario', 'id_evento'], name='idx_visitas_evento'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['titulo'], name='idx_video_titulo'),
        ),
        migrations.AddIndex(
            model_name='verificacionregistrousuario',
            index=models.Index(fields=['id_usuario'], name='idx_verifica_registro_usuario'),
        ),
        migrations.AddIndex(
            model_name='listareproduccionusuariovideos',
            index=models.Index(fields=['id_lista_reprod'], name='idx_lista_reprod_video'),
        ),
        migrations.AddIndex(
            model_name='listareproduccionusuario',
            index=models.Index(fields=['id_usuario'], name='idx_lista_reprod_usuario'),
        ),
        migrations.AddIndex(
            model_name='favoritosusuariovideo',
            index=models.Index(fields=['id_usuario', 'id_video'], name='idx_favoritos_video_usuario'),
        ),
        migrations.AddIndex(
            model_name='eventoacervo',
            index=models.Index(fields=['id_usuario'], name='idx_eventos_acervo_usuario'),
        ),
        migrations.AddIndex(
            model_name='eventoacervo',
            index=models.Index(fields=['titulo'], name='idx_eventos_acervo_titulo'),
        ),
        migrations.AddIndex(
            model_name='eventoacervo',
            index=models.Index(fields=['fechainicio', 'fechafin'], name='idx_eventos_acervo_fechas'),
        ),
        migrations.AddIndex(
            model_name='creditosvideo',
            index=models.Index(fields=['codigo_identificacion'], name='idx_codigo_ident_creditos'),
        ),
        migrations.AddIndex(
            model_name='creditosvideo',
            index=models.Index(fields=['direccion_realizacion'], name='idx_direccion_creditos'),
        ),
        migrations.AddIndex(
            model_name='creditosvideo',
            index=models.Index(fields=['guion'], name='idx_guion_creditos'),
        ),
        migrations.AddIndex(
            model_name='creditosvideo',
            index=models.Index(fields=['camara'], name='idx_camara_creditos'),
        ),
        migrations.AddIndex(
            model_name='creditosvideo',
            index=models.Index(fields=['musica'], name='idx_musica_creditos'),
        ),
        migrations.AddIndex(
            model_name='creditosvideo',
            index=models.Index(fields=['edicion'], name='idx_edicion_creditos'),
        ),
        migrations.AddIndex(
            model_name='creditosvideo',
            index=models.Index(fields=['produccion_ejecutiva'], name='idx_produccion_ej_creditos'),
        ),
        migrations.AddIndex(
            model_name='creditosadicionalesvideo',
            index=models.Index(fields=['formatos_disponibles'], name='idx_formatos_creditos'),
        ),
        migrations.AddIndex(
            model_name='comentariosvideo',
            index=models.Index(fields=['id_video', 'document_id'], name='idx_video_comentarios'),
        ),
        migrations.AddIndex(
            model_name='calificacionvideo',
            index=models.Index(fields=['id_video', 'id_usuario'], name='idx_calificacion_video'),
        ),
        migrations.AddIndex(
            model_name='calidadvideo',
            index=models.Index(fields=['titulo_calidad'], name='idx_calidadvideo_titulo'),
        ),
        migrations.AddIndex(
            model_name='calidadvideo',
            index=models.Index(fields=['dimensiones'], name='idx_calidadvideo_dimensiones'),
        ),
        migrations.AddIndex(
            model_name='calidadvideo',
            index=models.Index(fields=['resolucion'], name='idx_calidadvideo_resolucion'),
        ),
    ]
