# Generated by Django 4.1.2 on 2023-04-30 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administracion', '0001_Migracion_productiva_inicial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatoVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(null=True)),
                ('document_id', models.CharField(default='', max_length=128, unique=True)),
                ('visitas', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('id_autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatos_por_video', to='administracion.video')),
            ],
        ),
        migrations.AddIndex(
            model_name='relatovideo',
            index=models.Index(fields=['id_video', 'document_id'], name='idx_relato_comentarios'),
        ),
    ]
