# Generated by Django 4.1.2 on 2023-04-30 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administracion', '0002_Se_reparan_relatos_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitasRelato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitas', models.PositiveIntegerField(default=0)),
                ('id_relato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas_por_relato', to='administracion.relatovideo')),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_por_vista_relato', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavoritosUsuarioRelato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_relato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos_por_relato', to='administracion.relatovideo')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_por_favorito_relato', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='visitasrelato',
            index=models.Index(fields=['id_usuario', 'id_relato'], name='idx_visitas_relato'),
        ),
        migrations.AddIndex(
            model_name='favoritosusuariorelato',
            index=models.Index(fields=['id_usuario', 'id_relato'], name='idx_favoritos_relato_usuario'),
        ),
    ]
