# Generated by Django 4.1.2 on 2023-05-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_Se_reparan_visitas_favs_relatos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='titulo',
            field=models.CharField(max_length=500),
        ),
    ]
