# Generated by Django 4.1.2 on 2023-05-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_Atencion_Se_Quita_Unicidad_Video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='titulo',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
